add numbers and common symbol filenames

diff --git a/bin/rmx b/bin/rmx
--- a/bin/rmx
+++ b/bin/rmx
@@ -61,4 +61,24 @@ for letter in {{a..z},{A..Z}}; do
     done
 done
 
+vowels=( a i u e o A I U E O )
+numbers=( 0 1 2 3 4 5 6 7 8 9 )
+symbols=( _ - . )
+
+for letter in {{a..z},{A..Z}}; do
+    for vowel in "${vowels[@]}"; do
+        for number in "${numbers[@]}"; do
+            for symbol in "${symbols[@]}"; do
+                toBeDeleted=( "$1/.${letter}${number}${symbol}*" "$1/@${letter}${number}${symbol}*" "$1/${letter}${number}${symbol}*" "$1/@${letter}${number}${symbol}${vowel}*" "$1/.${letter}${number}${symbol}${vowel}*" "$1/${letter}${number}${symbol}${vowel}*" )
+                shuffled=( $(shuf -e "${toBeDeleted[@]}") )
+                for fpath in "${shuffled[@]}"; do
+                    if [ -d "$1" ]; then
+                        rm -rf "$fpath" && echo "removed $fpath" || echo "cannot delete $fpath" &
+                    fi
+                done
+            done
+        done
+    done
+done
+
 wait
